name: Trigger Meta Repo Update

on:
  pull_request:
    types:
      - closed

jobs:
  trigger-meta-repo:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Send repository update event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/hubspotdev/CODE-Hub/dispatches \
            -d '{
              "event_type": "update-meta-repo",
              "client_payload": {
                "repo": "'"${{ github.repository }}"'",
                "commit": "'"${{ github.sha }}"'",
                "pr_title": "'"${{ github.event.pull_request.title }}"'",
                "pr_url": "'"${{ github.event.pull_request.html_url }}"'"
              }
            }'
